/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

_If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.11
 */
import { faker } from '@faker-js/faker';
import { http, HttpResponse, delay } from 'msw';
import type { GetInventory200, Order } from '.././types';

export const getGetInventoryResponseMock = (): GetInventory200 => ({
  [faker.string.alphanumeric(5)]: faker.number.int({ min: undefined, max: undefined }),
});

export const getPlaceOrderResponseMock = (overrideResponse: any = {}): Order => ({
  complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  id: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  petId: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  quantity: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  shipDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['placed', 'approved', 'delivered'] as const),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetOrderByIdResponseMock = (overrideResponse: any = {}): Order => ({
  complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  id: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  petId: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  quantity: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
  shipDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['placed', 'approved', 'delivered'] as const),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetInventoryMockHandler = (overrideResponse?: GetInventory200) => {
  return http.get('*/store/inventory', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getGetInventoryResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getPlaceOrderMockHandler = (overrideResponse?: Order) => {
  return http.post('*/store/order', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getPlaceOrderResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getGetOrderByIdMockHandler = (overrideResponse?: Order) => {
  return http.get('*/store/order/:orderId', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getGetOrderByIdResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getDeleteOrderMockHandler = () => {
  return http.delete('*/store/order/:orderId', async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};
export const getStoreMock = () => [
  getGetInventoryMockHandler(),
  getPlaceOrderMockHandler(),
  getGetOrderByIdMockHandler(),
  getDeleteOrderMockHandler(),
];
